version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/perfume-pedia:latest
    container_name: perfume-pedia
    ports:
      - "8080:8080"  # 호스트:컨테이너 포트 매핑
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/perfumePedia?serverTimezone=UTC&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    volumes:
      - /home/argo/Perfume-project/Docker:/app/data  # 데이터 영구 저장
    depends_on:
      - db  # DB 컨테이너 먼저 실행
    networks:
      - perfume-network
    restart: unless-stopped  # 컨테이너 자동 재시작

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=perfumePedia
    volumes:
      - mysql_data:/var/lib/mysql  # MySQL 데이터 저장
    networks:
      - perfume-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  perfume-network:
    driver: bridge